package com.ubcsolar.ui;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import javax.swing.JSpinner;
import javax.swing.JSlider;
import javax.swing.SwingConstants;
import javax.swing.JLabel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

public class SliderSpinnerFrame extends JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7199207287395262736L;
	private JLabel topLabel; //the label at the top
	private JSlider slider = new JSlider(); //main slider
	private JSpinner spinner = new JSpinner();
	@SuppressWarnings("unused") //will implement later
	private boolean isManuallySet = false; //If the speed value is manually set instead of generated by the
									//simulator, we should change color or something. 
	private int currentValue; 
	
	
	public SliderSpinnerFrame(String labelAtTheTop, int initialValue, boolean isManuallySetInitialValue) {
		this.isManuallySet = isManuallySetInitialValue;
		currentValue = initialValue;
		JPanel panel = new JPanel();
		this.add(panel, BorderLayout.CENTER);
		panel.setLayout(new BorderLayout(0, 0));
		
		spinner = new JSpinner();
		spinner.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				currentValue = (int) spinner.getValue();
				isManuallySet = true;
				updateSelectors();
			}
		});
		spinner.setValue(initialValue);
		panel.add(spinner, BorderLayout.SOUTH);
		
		slider = new JSlider();
		slider.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent arg0) {
				currentValue = slider.getValue();
				isManuallySet = true;
				updateSelectors();
			}
		});
		slider.setMinorTickSpacing(25);
		slider.setMaximum(125);
		slider.setPaintTicks(true);
		slider.setPaintLabels(true);
		slider.setOrientation(SwingConstants.VERTICAL);
		slider.setValue(initialValue);
		panel.add(slider, BorderLayout.CENTER);
		
		topLabel = new JLabel("New label");
		topLabel.setHorizontalAlignment(SwingConstants.CENTER);
		topLabel.setText(labelAtTheTop);
		panel.add(topLabel, BorderLayout.NORTH);
		updateSelectors();
	}

	public int getValue(){
		return currentValue; 
	}
	
	public void setValue(int newValue){
		this.currentValue = newValue;
		this.updateSelectors();
	}

	private void updateSelectors() {
		this.slider.setValue(this.currentValue);
		this.spinner.setValue(this.currentValue);	
		
	}


}
