package com.ubcsolar.ui;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.util.*;

import javax.swing.JSpinner;
import javax.swing.JSlider;
import javax.swing.SwingConstants;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.event.ChangeListener;

import com.ubcsolar.common.GeoCoord;

import javax.swing.event.ChangeEvent;

public class SliderSpinnerFrame extends JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7199207287395262736L;
	private JLabel topLabel; //the label at the top
	private JSlider slider = new JSlider(); //main slider
	private JSpinner spinner = new JSpinner();
	private boolean isManuallySet = false; //If the speed value is manually set instead of generated by the
	

	//simulator, we should change color or something. 
	private int currentValue; 
	private List<GeoCoord> representedCoordinates;
	
	
	public SliderSpinnerFrame(String labelAtTheTop, int initialValue, boolean isManuallySetInitialValue, List<GeoCoord> representingCoords) {
		this.isManuallySet = isManuallySetInitialValue;
		currentValue = initialValue;
		this.representedCoordinates = representingCoords;
		JPanel panel = new JPanel();
		this.add(panel, BorderLayout.CENTER);
		panel.setLayout(new BorderLayout(0, 0));
		
		spinner = new JSpinner();
		spinner.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				currentValue = (int) spinner.getValue();
				isManuallySet = true;
				updateSelectors();
			}
		});
		spinner.setValue(initialValue);
		Component mySpinnerEditor = spinner.getEditor();
		JFormattedTextField jftf = ((JSpinner.DefaultEditor) mySpinnerEditor).getTextField();
		jftf.setColumns(3); //won't go faster than 999 km/h. 
		panel.add(spinner, BorderLayout.SOUTH);
		
		slider = new JSlider();
		slider.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent arg0) {
				currentValue = slider.getValue();
				isManuallySet = true;
				updateSelectors();
			}
		});
		slider.setMinorTickSpacing(25);
		slider.setMaximum(125);
		slider.setPaintTicks(true);
		slider.setPaintLabels(true);
		slider.setOrientation(SwingConstants.VERTICAL);
		slider.setValue(initialValue);
		panel.add(slider, BorderLayout.CENTER);
		
		topLabel = new JLabel("New label");
		topLabel.setHorizontalAlignment(SwingConstants.CENTER);
		topLabel.setText(labelAtTheTop);
		panel.add(topLabel, BorderLayout.NORTH);
		updateSelectors();
	}

	public int getValue(){
		return currentValue; 
	}
	
	public void setValue(int newValue){
		this.currentValue = newValue;
		this.updateSelectors();
	}

	private void updateSelectors() {
		this.slider.setValue(this.currentValue);
		this.spinner.setValue(this.currentValue);	
		
	}

	public List<GeoCoord> getRepresentedCoordinates() {
		return representedCoordinates;
	}

	public boolean isManuallySet() {
		return isManuallySet;
	}

}
